name: Publish Bleeding Edge Package

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy-package:
    if: >
      ${{ github.event.pull_request.merged == true && 
      contains(github.event.pull_request.labels.*.name, 'bleeding-edge') }}
    timeout-minutes: 45
    environment: bleeding-edge
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
      with:
        repository-url: https://test.pypi.org/legacy/
