name: Unit testing (EU1)

permissions:
  contents: read

on:
  push:
    paths:
      - '**.py'
    branches: 
      - main
      - 'ver_*'
  pull_request:
    paths:
      - '**.py'
    branches: 
      - main
      - 'ver_*'

jobs:
  eu1:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-24.04
    timeout-minutes: 45
    environment: testing-eu1
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip==24.0
        python -m pip install pytest==8.1.1 coverage==7.4.4
        pip install -r requirements.txt
    
    - name: Test with pytest
      env:
        DEBUG_API_ID: ${{ secrets.DEBUG_API_ID_EU1 }}
        DEBUG_API_SECRET: ${{ secrets.DEBUG_API_SECRET_EU1 }}
        DEBUG_API_BASE_URL: eu1
        CROSS_DEBUG_KEY: ${{ secrets.CROSS_DEBUG_KEY }}
        CROSS_DEBUG_SECRET: ${{ secrets.CROSS_DEBUG_SECRET }}
        DEBUG_NGSIEM_API_KEY: ${{ secrets.DEBUG_NGSIEM_API_KEY_EU1 }}
        DEBUG_NGSIEM_URL_KEY: ${{ secrets.DEBUG_NGSIEM_URL_KEY_EU1 }}
      run: |
        coverage run --source=src --omit=src/falconpy/debug.py -m pytest -s --ignore-glob=**/manual/*
        coverage report
