name: Unit testing (Ubuntu)

permissions:
  contents: read

on:
  push:
    paths:
      - '**.py'
    branches: 
      - main
      - 'ver_*'
      - dev
  pull_request:
    paths:
      - '**.py'
    branches: 
      - main
      - 'ver_*'
      - dev

jobs:
  build:
    if: github.event.pull_request.head.repo.full_name == github.repository
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14-dev']
    runs-on: ubuntu-24.04
    timeout-minutes: 45
    environment: testing
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0
      with:
        persist-credentials: false
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip==24.0
        python -m pip install pytest==8.1.1 coverage==7.4.4
        pip install -r requirements.txt
    
    - name: Test with pytest
      env:
        DEBUG_API_ID: ${{ secrets.DEBUG_API_ID }}
        DEBUG_API_SECRET: ${{ secrets.DEBUG_API_SECRET }}
        CROSS_DEBUG_KEY: ${{ secrets.CROSS_DEBUG_KEY }}
        CROSS_DEBUG_SECRET: ${{ secrets.CROSS_DEBUG_SECRET }}
        DEBUG_NGSIEM_API_KEY: ${{ secrets.DEBUG_NGSIEM_API_KEY_US1 }}
        DEBUG_NGSIEM_URL_KEY: ${{ secrets.DEBUG_NGSIEM_URL_KEY_US1 }}
      run: |
        coverage run --source=src --omit=src/falconpy/debug.py -m pytest -s --ignore-glob=**/manual/*
        coverage report
